title: Formation R
tagline: chez Quantmetry
logo: assets/img/LOGO_quantmetry.jpg 
owner: Arthur Flam
author:
  email: arthur.flam@gmail.com
  github: arthur-flam
  firstname: Arthur
  lastname: Flam

social:
  github: arthur-flam
  twitter: ArthurFlam

# Choose url: / for local development
url: http://arthur-flam.github.com/blog/
rawurl: https://raw.github.com/arthur-flam/blog/gh-pages/
# url: /
URL: http://github.com/arthur-flam/blog/
navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}
